steps:
  - name: node
    entrypoint: npm
    args: ["install"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/web-dev-test-379414/web-dev-server:0.0.1"
      - "."
images:
  - "gcr.io/web-dev-test-379414/web-dev-server:0.0.1"
